### ISSUE TITLE
Compilation failed

### ISSUE THREAD

**Issue by Liphtier** [m6w6/ext-raphf#6]
Fails to compile on PHP 7.0.25

`
# pecl install raphf
downloading raphf-2.0.0.tgz ...
Starting to download raphf-2.0.0.tgz (15,715 bytes)
......done: 15,715 bytes
8 source files, building
running: phpize
Configuring for:
PHP Api Version:         20151012
Zend Module Api No:      20151012
Zend Extension Api No:   320151012
running: rm aclocal.m4
running: autoreconf
building in /tmp/pear-build-rootB3wt9v/raphf-2.0.0
running: /tmp/raphf/configure --with-php-config=/usr/bin/php-config
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for a sed that does not truncate output... /bin/sed
checking for cc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking how to run the C preprocessor... cc -E
checking for icc... no
checking for suncc... no
checking whether cc understands -c and -o together... yes
checking for system library directory... lib
checking if compiler supports -R... no
checking if compiler supports -Wl,-rpath,... yes
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking target system type... x86_64-pc-linux-gnu
checking for PHP prefix... /usr/lib64/php7.0
checking for PHP includes... -I/usr/lib64/php7.0/include/php -I/usr/lib64/php7.0/include/php/main -I/usr/lib64/php7.0/include/php/TSRM -I/usr/lib64/php7.0/include/php/Zend -I/usr/lib64/php7.0/include/php/ext -I/usr/lib64/php7.0/include/php/ext/date/lib
checking for PHP extension directory... /usr/lib64/php7.0/lib/extensions/debug-zts-20151012
checking for PHP installed headers prefix... /usr/lib64/php7.0/include/php
checking if debug is enabled... yes
checking if zts is enabled... yes
checking for re2c... re2c
checking for re2c version... 0.16 (ok)
checking for gawk... gawk
checking whether to enable raphf support... yes, shared
checking how to print strings... printf
checking for a sed that does not truncate output... (cached) /bin/sed
checking for fgrep... /bin/grep -F
checking for ld used by cc... /usr/x86_64-pc-linux-gnu/bin/ld
checking if the linker (/usr/x86_64-pc-linux-gnu/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/x86_64-pc-linux-gnu/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking for gawk... (cached) gawk
checking command to parse /usr/bin/nm -B output from cc object... ok
checking for sysroot... no
checking for a working dd... /bin/dd
checking how to truncate binary pipes... /bin/dd bs=4096 count=1
checking for mt... no
checking if : is a manifest tool... no
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if cc supports -fno-rtti -fno-exceptions... no
checking for cc option to produce PIC... -fPIC -DPIC
checking if cc PIC flag -fPIC -DPIC works... yes
checking if cc static flag -static works... yes
checking if cc supports -c -o file.o... yes
checking if cc supports -c -o file.o... (cached) yes
checking whether the cc linker (/usr/x86_64-pc-linux-gnu/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no
configure: creating ./config.status
config.status: creating config.h
config.status: executing libtool commands
running: make
/bin/sh /tmp/pear-build-rootB3wt9v/raphf-2.0.0/libtool --mode=compile cc  -I. -I/tmp/raphf -DPHP_ATOM_INC -I/tmp/pear-build-rootB3wt9v/raphf-2.0.0/include -I/tmp/pear-build-rootB3wt9v/raphf-2.0.0/main -I/tmp/raphf -I/usr/lib64/php7.0/include/php -I/usr/lib64/php7.0/include/php/main -I/usr/lib64/php7.0/include/php/TSRM -I/usr/lib64/php7.0/include/php/Zend -I/usr/lib64/php7.0/include/php/ext -I/usr/lib64/php7.0/include/php/ext/date/lib -I/tmp/raphf/src  -DHAVE_CONFIG_H  -g -O0   -c /tmp/raphf/src/php_raphf_api.c -o src/php_raphf_api.lo
/tmp/pear-build-rootB3wt9v/raphf-2.0.0/libtool: line 934: X--mode=compile: command not found
/tmp/pear-build-rootB3wt9v/raphf-2.0.0/libtool: line 1101: *** Warning: inferring the mode of operation is deprecated.: command not found
/tmp/pear-build-rootB3wt9v/raphf-2.0.0/libtool: line 1102: *** Future versions of Libtool will require --mode=MODE be specified.: command not found
/tmp/pear-build-rootB3wt9v/raphf-2.0.0/libtool: line 1245: Xcc: command not found
/tmp/pear-build-rootB3wt9v/raphf-2.0.0/libtool: line 1245: X-I.: command not found
/tmp/pear-build-rootB3wt9v/raphf-2.0.0/libtool: line 1245: X-I/tmp/raphf: No such file or directory
/tmp/pear-build-rootB3wt9v/raphf-2.0.0/libtool: line 1245: X-DPHP_ATOM_INC: command not found
/tmp/pear-build-rootB3wt9v/raphf-2.0.0/libtool: line 1245: X-I/tmp/pear-build-rootB3wt9v/raphf-2.0.0/include: No such file or directory
/tmp/pear-build-rootB3wt9v/raphf-2.0.0/libtool: line 1245: X-I/tmp/pear-build-rootB3wt9v/raphf-2.0.0/main: No such file or directory
/tmp/pear-build-rootB3wt9v/raphf-2.0.0/libtool: line 1245: X-I/tmp/raphf: No such file or directory
/tmp/pear-build-rootB3wt9v/raphf-2.0.0/libtool: line 1245: X-I/usr/lib64/php7.0/include/php: No such file or directory
/tmp/pear-build-rootB3wt9v/raphf-2.0.0/libtool: line 1245: X-I/usr/lib64/php7.0/include/php/main: No such file or directory
/tmp/pear-build-rootB3wt9v/raphf-2.0.0/libtool: line 1245: X-I/usr/lib64/php7.0/include/php/TSRM: No such file or directory
/tmp/pear-build-rootB3wt9v/raphf-2.0.0/libtool: line 1245: X-I/usr/lib64/php7.0/include/php/Zend: No such file or directory
/tmp/pear-build-rootB3wt9v/raphf-2.0.0/libtool: line 1245: X-I/usr/lib64/php7.0/include/php/ext: No such file or directory
/tmp/pear-build-rootB3wt9v/raphf-2.0.0/libtool: line 1245: X-I/usr/lib64/php7.0/include/php/ext/date/lib: No such file or directory
/tmp/pear-build-rootB3wt9v/raphf-2.0.0/libtool: line 1245: X-I/tmp/raphf/src: No such file or directory
/tmp/pear-build-rootB3wt9v/raphf-2.0.0/libtool: line 1245: X-DHAVE_CONFIG_H: command not found
/tmp/pear-build-rootB3wt9v/raphf-2.0.0/libtool: line 1245: X-g: command not found
/tmp/pear-build-rootB3wt9v/raphf-2.0.0/libtool: line 1245: X-O0: command not found
/tmp/pear-build-rootB3wt9v/raphf-2.0.0/libtool: line 1245: X-c: command not found
/tmp/pear-build-rootB3wt9v/raphf-2.0.0/libtool: line 1298: Xsrc/php_raphf_api.lo: No such file or directory
/tmp/pear-build-rootB3wt9v/raphf-2.0.0/libtool: line 1303: libtool: compile: cannot determine name of library object from `': command not found
make: *** [Makefile:213: src/php_raphf_api.lo] Error 1
ERROR: `make' failed
`

**Comment by m6w6** [comment]
Looking at all those `X`s in your log, I suspect something weird going one with your environment or command line tools...?
